name: Build Armbian Images
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # ubuntu-24.04-arm, ubuntu-24.04-riscv
    strategy:
      fail-fast: false
      matrix:
        board:
          - "orangepi5-max"
          - "orangepi5-plus"
          - "orangepi5-ultra"
          - "orangepi5"
          - "orangepi5b"
          - "orangepi5pro"
          - "rock-5c"
    permissions:
      contents: write # required for armbian/build action to upload artifacts
    steps:
      - uses: armbian/build@main
        with:
          armbian_token: ${{ secrets.GITHUB_TOKEN }}
          armbian_board: ${{ matrix.board }} # orangepi5 bananapif3
          armbian_release: "trixie" # trixie
          armbian_target: "build"
          armbian_kernel_branch: "vendor"
          armbian_ui: "minimal" # server xfce
          armbian_runner_clean: "yes" # recommended for Github runners